[[header]]
:description: RISC-V Wait-on-Reservation-Set (Zawrs) extension
:company: RISC-V.org
:revdate: 6/2022
:revnumber: 1.0
:revremark: This document is in development. Assume everything can change. See http://riscv.org/spec-state for details.
:url-riscv: http://riscv.org
:doctype: book
:preface-title: Preamble
:colophon:
:appendix-caption: Appendix
:imagesdir: images
:title-logo-image: image:risc-v_logo.svg[pdfwidth=3.25in,align=center]
// Settings:
:experimental:
:reproducible:
// needs to be changed? bug discussion started
//:WaveDromEditorApp: app/wavedrom-editor.app
:imagesoutdir: images
//:bibtex-file: zawrs.bib
//:bibtex-order: alphabetical
//:bibtex-style: apa
:icons: font
:lang: en
:listing-caption: Listing
:sectnums:
:toc: left
:toclevels: 4
:source-highlighter: pygments
ifdef::backend-pdf[]
:source-highlighter: coderay
endif::[]
:data-uri:
:hide-uri-scheme:
:stem: latexmath
:footnote:
:xrefstyle: short

= RISC-V Wait-on-Reservation-Set (Zawrs) extension
Ved Shanbhogue

// Preamble
[WARNING]
.This document is in the link:http://riscv.org/spec-state[Development state]
====
Assume everything can change. This draft specification will change before 
being accepted as standard, so implementations made to this draft 
specification will likely not conform to the future standard.
====
[preface]
=== Copyright and license information
This specification is licensed under the Creative Commons 
Attribution 4.0 International License (CC-BY 4.0). The full 
license text is available at
https://creativecommons.org/licenses/by/4.0/.

Copyright 2022 by RISC-V International.

[preface]
=== Contributors

This RISC-V specification has been contributed to directly or indirectly by:

Aaron Durbin, Abel Bernabeu, Allen Baum, Christoph Müllner, David Weaver, Greg Favor, Josh Scheid, Ken Dockser, Paul Donahue, Phil McCoy, Philipp Tomsich, Tariq Kurd, Ved Shanbhogue

== Introduction
The Zawrs extension defines a pair of instructions to be used in polling loops 
that allows a core to enter a low-power state and wait on a store to a memory 
location. Waiting for a memory location to be updated is a common pattern in 
many use cases such as:

. Contenders for a lock waiting for the lock variable to be updated.

. Consumers waiting on the tail of an empty queue for the producer to queue 
  work/data. The producer may be code executing on a RISC-V hart, an accelerator
  device, an external I/O agent.

. Code waiting on a flag to be set in memory indicative of an event occurring. 
  For example, software on a RISC-V hart may wait on a "done" flag to be set in
  memory by an accelerator device indicating completion of a job previously 
  submitted to the device.

Such use cases involve polling on memory locations, and such busy loops can be a
wasteful expenditure of energy. To mitigate the wasteful looping in such usages,
a `WRS.NTO` (WRS-with-no-timeout) instruction is provided. Instead of polling 
for a store to a specific memory location, software registers a reservation set
that includes all the bytes of the memory location using the `LR` instruction. 
Then a subsequent `WRS.NTO` instruction would cause the hart to temporarily 
stall execution in a low-power state until a store occurs to the reservation set
or an interrupt is observed.

Sometimes the program waiting on a memory update may also need to carry out a
task at a future time or otherwise place an upper bound on the wait. To support
such use cases a second instruction `WRS.STO` (WRS-with-short-timeout) is 
provided that works like `WRS.NTO` but bounds the stall duration to an 
implementation-define short timeout such that the stall is terminated on the 
timeout if no other conditions have to occurred to terminate the stall. The 
program using this instruction may then determine if its deadline has been 
reached.

[NOTE]
====
The instructions in the Zawrs extension are only useful in conjunction with the
LR instructions, which are provided by the A extension, and which we also expect
to be provided by a narrower Zalrsc extension in the future.
====

include::zawrs.adoc[]
