[[Zawrs]]
== Zawrs

The `WRS.NTO` and `WRS.STO` instructions are available in all privilege modes 
and use the `SYSTEM` major opcode. When these instructions are invoked, the 
hart stalls until one of following events occur:

. The reservation set is invalid
. If `WRS.STO`, an implementation defined short time has passed since the 
  hart was stalled.
. An interrupt was observed - even if disabled

*Encoding:*
[wavedrom, , ]
....
{reg: [
  {bits: 7, name: 'opcode', attr: ['SYSTEM(0x73)'] },
  {bits: 5, name: 'rd', attr: ['0'] },
  {bits: 3,  name: 'funct3', attr: ['0'] },
  {bits: 5,  name: 'rs1', attr: ['0'] },
  {bits: 12,  name: 'funct12', attr:['WRS.NTO(0x0d)', 'WRS.STO(0x1d)'] },
], config:{lanes: 1, hspace:1024}}
....

*Operation:*
[source,asciidoc, linenums]
....
if reservation-set is valid
   Stall hart execution until one of following events occur:
      a) reservation set is invalid 
      b) if WRS.STO, a short time since start of stall has elapsed
      c) interrupt observed 
....

While stalled, an implementation is permitted to remove the stall and complete 
execution occasionally for any reason. `WRS.NTO` and `WRS.STO` are allowed to 
complete in a bounded amount of time from when the condition to remove the 
stall occurs. These instructions are not supported in a constrained `LR`/`SC` loop.

[NOTE]
====
Architecture Comment: `WRS.STO` and `WRS.NTO` are not defined as a hint but 
as having a defined behavior.  Implementing as a hint that can be ignored 
(i.e., executed as the underlying nop) may lead to degradation in the system
and/or application performance.

Architecture Comment: Since the `WRS.STO` and `WRS.NTO` instructions can complete 
execution for reasons other than writes to the reservation set, software will 
likely need a means of looping until the required writes have occurred.

Recommendation: An implementation should try to bound the short timeout to
be long enough to allow meaningful power reduction but short enough to avoid 
a program using the timeout to meet a deadline from missing it significantly. 
Bounding the short timeout to not more than 10 microseconds is recommended.

Recommendation: An implementation should try to bound the latency to remove the
stall to latency incurred on access to an on-chip cache furthest from the hart 
or in case of a cache-less system the access to main memory from the hart
====
`WRS.NTO` and `WRS.STO` instructions follows rules of the existing `WFI` 
instruction for resuming execution on a pending  interrupt.

When the existing `TW` (Timeout Wait) bit in `mstatus` is set and `WRS.NTO` is 
executed in S or U  mode, and it does not complete within an 
implementation-specific bounded time limit, the `WRS.NTO` instruction will cause
an illegal instruction exception.

When executing in VS or VU mode, if the existing `VTW` bit is set in `hstatus`,
the `mstatus` `TW` bit is clear, and the `WRS.NTO` does not complete within an
implementation-specific bounded time limit, the `WRS.NTO` instruction will 
cause a virtual instruction exception.
