[[Zawrs]]
== Zawrs

The `WRS.NTO` and `WRS.STO` instructions cause the hart to temporarily stall
execution in a low-power state until one of the following events occur:

. The reservation set is invalid
. If `WRS.STO`, an implementation defined short time has passed since the 
  hart stalled execution.
. An interrupt was observed - even if disabled

These instructions are available in all privilege modes.

*Encoding:*
[wavedrom, , ]
....
{reg: [
  {bits: 7, name: 'opcode', attr: ['SYSTEM(0x73)'] },
  {bits: 5, name: 'rd', attr: ['0'] },
  {bits: 3,  name: 'funct3', attr: ['0'] },
  {bits: 5,  name: 'rs1', attr: ['0'] },
  {bits: 12,  name: 'funct12', attr:['WRS.NTO(0x0d)', 'WRS.STO(0x1d)'] },
], config:{lanes: 1, hspace:1024}}
....

*Operation:*
[source,asciidoc, linenums]
....
if reservation set is valid
   Stall hart execution until one of the following events occur:
      a) The reservation set is invalid 
      b) If WRS.STO, a short time since start of stall has elapsed
      c) An interrupt is observed 
....

While stalled, an implementation is permitted to occasionally terminate the 
stall and complete execution for any reason. 

These instructions are not supported in a constrained `LR`/`SC` loop.

[NOTE]
====
Architecture Comment: `WRS.STO` and `WRS.NTO` are not defined as hints but 
as having defined behaviors.  Implementing as a hint that can be ignored 
(i.e., executed as a nop) may lead to degradation in the system and/or 
application performance.

Architecture Comment: Since the `WRS.STO` and `WRS.NTO` instructions can 
complete execution for reasons other than stores to the reservation set,
software will likely need a means of looping until the required stores 
have occurred.

Recommendation: The duration of a WRS.STO instruction's timeout may vary
significantly within and among implementations. In a typical implementation
this duration should be long enough to allow meaningful power reduction but
short enough to avoid a program using the timeout to meet a deadline from
missing it significantly. A duration less than or equal to 10 microseconds
is recommended.

Recommendation: An implementation should try to bound the latency to terminate
the stall, from when the conditions to terminate the stall have been observed,
to the latency incurred on access to an on-chip cache furthest from the hart 
or in case of a cache-less system the access to main memory from the hart.
====
`WRS.NTO` and `WRS.STO` instructions follow the rules of the `WFI` instruction
for resuming execution on a pending  interrupt.

When the `TW` (Timeout Wait) bit in `mstatus` is set and `WRS.NTO` is executed
in S or U  mode, and it does not complete within an implementation-specific 
bounded time limit, the `WRS.NTO` instruction will cause an illegal instruction
exception.

When executing in VS or VU mode, if the `VTW` bit is set in `hstatus`, the 
`mstatus` `TW` bit is clear, and the `WRS.NTO` does not complete within an 
implementation-specific bounded time limit, the `WRS.NTO` instruction will cause
a virtual instruction exception.
